plugins {
	id "java-gradle-plugin"
	id "io.spring.javaformat" version "${javaFormatVersion}"
}

dependencies {
	implementation("io.spring.javaformat:spring-javaformat-gradle-plugin:${javaFormatVersion}")
	implementation("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")

	testImplementation(platform("org.junit:junit-bom:${junitJupiterVersion}"))
	testImplementation("org.assertj:assertj-core:${assertjVersion}")
	testImplementation("org.junit.jupiter:junit-jupiter")
	testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

test {
	useJUnitPlatform()
}

gradlePlugin {
	plugins {
		conventionsPlugin {
			id = "org.v31bank.conventions"
			implementationClass = "org.v31bank.build.ConventionsPlugin"
		}
		deployedPlugin {
			id = "org.v31bank.deployed"
			implementationClass = "org.v31bank.build.DeployedPlugin"
		}
		integrationTestPlugin {
			id = "org.v31bank.integration-test"
			implementationClass = "org.v31bank.build.test.IntegrationTestPlugin"
		}
		starterPlugin {
			id = "org.v31bank.starter"
			implementationClass = "org.v31bank.build.starters.StarterPlugin"
		}
	}
}

