spring:
  application:
    name: V31-customer-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: wangxiang
    password: ""
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081
